term_reward_threshold: -8000.0
run_mode: maml
log_directory: ./
env_name: MediumWorld-v0
task_seed: 6969
start_seed: 69
test_task_seed: 69
test_start_seed: 69
render: false
n_cpu: 4
eval_plot_interval: 50
eval_save_interval: 50
eval_test_interval: 1
n_tasks: 1
n_grad_steps: 1
n_epochs: 1
n_parallel_envs: 20
batch_timesteps: 6
env_max_timesteps: 0
single_sampling: 0
n_optimization_epochs: 10
n_optimization_batches: 1
optimizer: Adam
shuffle_samples: 1
n_updates_per_batch: 16
eval_grad_steps:
- 0
- 1
first_order: false
alpha: 1.0
beta: 0.0003
inner_alg: PPO
inner_optimizer: SGD
meta_alg: PPO
meta_optimizer: SGD
vf_coef: 0.5
ent_coef: 0.0
max_grad_norm: 0.5
clip_range: 0.2
gamma: 0.99
lam: 0.95
dpi: 150
change_colors: 0
change_dynamics: 0
no_state_dict: 0
no_maml_apply_gradient: 0
no_task_resample: 0
debug_params: 0
debug_apply_gradient: 0
